window.IQTICI_PORT_STATE = {
  updated: "2026-02-16T23:05:00Z",
  port_branch: "master-mici-tici-redo",
  base_branch: "sync-20251218-tici @ 5ac160222",
  release_ref: "master-mici @ 9c2302e71534c6184c04985beac66f7b1f267ff8",
  replay_summary: "IQ commits in release range: 108; replayed/adapted on tici: 81; opendbc-only commits handled via targeted submodule port",
  opendbc_port: "f936514305ec26ec3efa085da9eccc0cb7b281b5 (branch iqpilot-tici-vw-tesla-port)",
  panda_port: "e66dd61526dfce2ce310d9e13ebe3f7cb1360704 (branch iqpilot-tici-no-sunny-opendbc)",
  build: "scons OK (macOS, .venv) @ 2026-02-16T20:29:25Z; longitudinal_mpc_lib target OK @ 2026-02-16T22:43:00Z; CI non-required LFS + Darwin toolchain binaries stored in normal git",
  tests: "pytest OK: common/tests/test_params.py + sunnypilot/mads/tests/test_mads_state_machine.py (23 passed) @ 2026-02-16T18:34:16Z",
  steps: [
    { status: "done", name: "IQ Delta Inventory", note: "Enumerated commit+file delta from release (108 commits, file-level mapping)." },
    { status: "done", name: "Clean Replay Onto tici Base", note: "Replayed IQ-only commits onto sync-20251218-tici, resolving platform conflicts with tici-safe merges." },
    { status: "done", name: "Sunnylink Removal", note: "Removed Sunnylink modules/hooks and retained Konn3kt replacement paths." },
    { status: "done", name: "Konn3kt + Pairing", note: "Ported Konn3kt stack, pairing dialogs, prime state integration, and registration flow changes." },
    { status: "done", name: "Proprietary Loader + Bundles", note: "Ported proprietary loader, hephaestusd/navd private artifacts, and install/verify scripts." },
    { status: "done", name: "UI/UX Parity", note: "Ported IQ-specific branding, settings, translations, icons/fonts, and onboarding/device flows." },
    { status: "done", name: "Post-port UI Startup Fixes", note: "Resolved missing UI imports/APIs by syncing release files and adding missing steering sub-layouts + params key for Offroad_StorageMissing." },
    { status: "done", name: "Gitea CI Migration", note: "Ported .gitea workflows and removed .github workflows/templates." },
    { status: "done", name: "VW/Tesla Superproject Edits", note: "Ported IQ-side controls/UI/logic changes in openpilot tree." },
    { status: "done", name: "VW/Tesla opendbc Targeted Port", note: "From opendbc base commit, imported only VW/Tesla-related files from release opendbc commit and pushed dedicated branch." },
    { status: "done", name: "GitHub/Sunnypilot Ref Cleanup", note: "Removed all github.com/sunnypilot and ghcr.io/sunnypilot references; removed external .lfsconfig override." },
    { status: "done", name: "panda Dependency Cleanup", note: "Repointed panda pyproject opendbc dependency to gitlvb and pushed dedicated branch." },
    { status: "done", name: "Compile + Tests", note: "scons passes; focused pytest suite passes on redo branch." },
    { status: "done", name: "Push Port Branch", note: "Pushed master-mici-tici-redo and force-updated master-mici-tici to same commit." }
  ],
  log: [
    "Initialized redo branch from sync-20251218-tici and fetched release master-mici for deterministic replay.",
    "Replayed IQ commit range while resolving conflicts with tici-aware merges; held opendbc pointer for targeted handling.",
    "Created opendbc targeted branch iqpilot-tici-vw-tesla-port from base SHA and imported VW/Tesla-only file set from release SHA.",
    "Created panda cleanup branch iqpilot-tici-no-sunny-opendbc and updated pyproject dependency URL.",
    "Applied post-replay cleanup for LFS endpoint neutrality and Sunnypilot/GitHub reference removal.",
    "Build and focused regression tests completed successfully on redo branch.",
    "Pushed master-mici-tici-redo and updated master-mici-tici to the same corrected commit.",
    "Resolved local compile blocker: panda F4 linker RAM overflow during scons; fixed by tuning queue sizes in panda/board/drivers/can_common.h for non-H7 targets, then revalidated successful full scons build.",
    "Patched IQ UI import chain failures reported on tici branch: restored OnroadBrightness display settings implementation, synced mici button API (icon_size/icon_offset), added missing steering_sub_layouts lane_change/torque modules, and synced sunnypilot list_view implementation.",
    "Added missing Params key Offroad_StorageMissing to common/params_keys.h and rebuilt; UI now starts past prior import/key crashes (remaining DBus warnings are expected when running UI standalone on macOS host).",
    "Fixed CI build failure caused by LFS pointer checkout of third_party/catch2/include/catch2/catch.hpp: removed catch.hpp LFS tracking from .gitattributes and committed full header blob to regular git so CI with lfs:false compiles tests.",
    "Fixed subsequent CI failure on model metadata generation from ONNX pointer files: switched checkout to lfs:true, kept submodule smudge disabled for speed, added required root ONNX git lfs pull and hard fail if dmonitoring_model.onnx/driving_policy.onnx are still LFS pointers.",
    "Adjusted CI per project policy: disabled required LFS at checkout again (lfs:false), removed hard LFS fetch dependency, and explicitly marked catch2 + modeld ONNX blobs as non-LFS in .gitattributes, committing real binary blobs for those files.",
    "Fixed subsequent CI break in longitudinal_mpc generation (`t_renderer` executed as LFS pointer) by explicitly excluding Darwin build-critical binaries from LFS and committing full blobs: acados t_renderer + Darwin acados dylibs + Darwin libyuv/raylib archives.",
    "Re-verified branch alignment and target build: origin/master-mici-tici == ed6eedaea (Everything up-to-date on push); local scons target `selfdrive/controls/lib/longitudinal_mpc_lib/c_generated_code/Makefile` succeeds with no t_renderer pointer failure.",
    "Fixed fresh-clone failure on device (`docs/assets/icon-star-empty.svg` missing LFS object 404): added `.gitattributes` path override and re-committed that SVG as a normal git blob."
  ]
};
